# Generated by Django 4.2.20 on 2026-06-03 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('smartphone', 'هاتف ذكي'), ('tablet', 'جهاز لوحي'), ('laptop', 'حاسوب محمول'), ('smartwatch', 'ساعة ذكية'), ('gaming_console', 'جهاز ألعاب'), ('camera', 'كاميرا')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('new', 'جديد'), ('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'مقبول'), ('poor', 'ضعيف')], max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('imei_1_encrypted', models.TextField(blank=True, default='')),
                ('imei_1_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('imei_2_encrypted', models.TextField(blank=True, default='')),
                ('imei_2_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('serial_encrypted', models.TextField(blank=True, default='')),
                ('serial_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('trust_score', models.PositiveSmallIntegerField(default=50)),
                ('trust_level', models.CharField(choices=[('excellent', 'ممتاز'), ('high', 'عالٍ'), ('medium', 'متوسط'), ('low', 'منخفض')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'db_table': 'products_product',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('transfer_type', models.CharField(choices=[('initial', 'تسجيل أولي'), ('purchase', 'شراء'), ('gift', 'هدية'), ('trade', 'مبادلة'), ('other', 'أخرى')], default='initial', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownership_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='products.product')),
            ],
            options={
                'verbose_name': 'سجل ملكية',
                'verbose_name_plural': 'سجلات الملكية',
                'db_table': 'products_ownership_record',
                'ordering': ['start_date'],
            },
        ),
    ]
