# Generated by Django 4.2.20 on 2026-06-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershiprecord',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_records', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='ownershiprecord',
            index=models.Index(fields=['product', 'is_current'], name='products_ow_product_6a4a42_idx'),
        ),
    ]
