# Generated by Django 4.2.20 on 2026-06-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'جديد'), ('used', 'مستعمل'), ('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'مقبول'), ('poor', 'ضعيف')], max_length=15),
        ),
    ]
