# Generated by Django 4.2.20 on 2026-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_condition_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
