# Generated by Django 4.2.20 on 2026-06-03 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('otp_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('login', 'تسجيل الدخول'), ('register', 'إنشاء حساب')], max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'رمز التحقق',
                'verbose_name_plural': 'رموز التحقق',
                'db_table': 'accounts_otp_verification',
                'indexes': [models.Index(fields=['phone_hash', 'purpose', 'is_used'], name='accounts_ot_phone_h_fb7f6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number_encrypted', models.TextField()),
                ('phone_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user_type', models.CharField(choices=[('individual', 'فرد'), ('business', 'جهة تجارية')], max_length=20)),
                ('national_id_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('iqama_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('identity_submitted', models.BooleanField(default=False)),
                ('absher_verified', models.BooleanField(default=False)),
                ('absher_verified_at', models.DateTimeField(blank=True, null=True)),
                ('cr_number_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cr_submitted', models.BooleanField(default=False)),
                ('wathiq_verified', models.BooleanField(default=False)),
                ('device_fingerprint_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'accounts_user',
            },
        ),
    ]
