# Generated by Django 4.2.20 on 2026-07-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('login', 'تسجيل الدخول'), ('register', 'إنشاء حساب'), ('seller_confirm', 'تأكيد عملية بيع (رابط عام)')], max_length=20),
        ),
    ]
