# Generated by Django 4.2.20 on 2026-06-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('certificate_type', models.CharField(choices=[('ownership_transfer', 'شهادة نقل ملكية'), ('current_ownership', 'شهادة ملكية حالية'), ('history_report', 'تقرير تاريخ المنتج')], max_length=20)),
                ('qr_code_path', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_path', models.CharField(blank=True, default='', max_length=255)),
                ('verification_url', models.CharField(blank=True, default='', max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='products.product')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'شهادة',
                'verbose_name_plural': 'الشهادات',
                'db_table': 'certificates_certificate',
                'ordering': ['-issued_at'],
            },
        ),
    ]
