# Generated by Django 4.2.20 on 2026-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_value', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'certificates_sequence',
            },
        ),
    ]
