# Generated by Django 4.2.20 on 2026-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('duplicate_imei', 'IMEI مكرر'), ('duplicate_serial', 'رقم تسلسلي مكرر'), ('excessive_transfers', 'تحويلات مفرطة'), ('excessive_registrations', 'تسجيلات مفرطة'), ('suspicious_activity', 'نشاط مشبوه')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالٍ'), ('critical', 'حرج')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('investigating', 'قيد التحقيق'), ('resolved', 'محلول'), ('dismissed', 'مرفوض')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تنبيه احتيال',
                'verbose_name_plural': 'تنبيهات الاحتيال',
                'db_table': 'fraud_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
