# Generated by Django 4.2.20 on 2026-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='device_condition',
            field=models.CharField(blank=True, choices=[('new', 'جديد'), ('used', 'مستعمل')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_terms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
