# Generated by Django 4.2.20 on 2026-07-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_direct_purchase_seller_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='seller_id_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
