# Generated by Django 4.2.20 on 2026-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_seller_id_number_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='seller_mobile_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
